export default interface quizProps {
    quizTitle: string;
    quizURL: string;
    quizPoints: number;
    quizAvailableFrom: string;
    quizAvailableTil: string;
    quizDue: string;
    quizDetails: string;
    quizNumQuestions: number;
    quizType: string;
    assignmentGroup: string;
    shuffleAnswers: boolean;
    timeLimit: number;
    multipleAttempts: boolean;
    attempts: number;
    showCorrectAnswers: boolean;
    accessCode: string;
    oneQAtATime: boolean;
    webcamRequired: boolean;
    lockQAfterAnswer: boolean;
    published: boolean;
};